package main

func main() {
	pdfApi := initPdfApi()

	AppendNewWatermark(pdfApi, PDF_DOCUMENT, IMAGE_FILE, IMAGE_OPACITY, IMAGE_ROTATE, IMAGE_X, IMAGE_Y, IMAGE_WIDTH, IMAGE_HEIGHT, PDF_OUTPUT, REMOTE_FOLDER)

	GetWatermarks(pdfApi, PDF_DOCUMENT_WITH_WATERMARKS, REMOTE_FOLDER)

	DeleteImageWatermarks(pdfApi, PDF_DOCUMENT_WITH_WATERMARKS, IMAGE_IDS_DEL, PDF_OUTPUT, REMOTE_FOLDER)

}
