package main

func main() {
	pdfApi := initPdfApi()

	appendHighlightAnnotation(pdfApi, PDF_DOCUMENT, PDF_OUTPUT_HIGHLIGHT, PAGE_NUMBER, NEW_HIGHLIGHT_TEXT, NEW_HIGHLIGHT_SUBJECT, NEW_HIGHLIGHT_CONTENTS, NEW_HIGHLIGHT_DESCRIPTION, &LINK_RECT, REMOTE_FOLDER)

	appendStrikeoutAnnotation(pdfApi, PDF_DOCUMENT, PDF_OUTPUT_STRIKEOUT, PAGE_NUMBER, NEW_STRIKEOUT_TEXT, NEW_STRIKEOUT_SUBJECT, NEW_STRIKEOUT_CONTENTS, NEW_STRIKEOUT_DESCRIPTION, &LINK_RECT, REMOTE_FOLDER)

	appendFreeTextAnnotation(pdfApi, PDF_DOCUMENT, PDF_OUTPUT_FREETEXT, PAGE_NUMBER, NEW_FREETEXT_TEXT, NEW_FREETEXT_SUBJECT, NEW_FREETEXT_CONTENTS, NEW_FREETEXT_DESCRIPTION, &LINK_RECT, REMOTE_FOLDER)

	appendUnderlineAnnotation(pdfApi, PDF_DOCUMENT, PDF_OUTPUT_UNDERLINE, PAGE_NUMBER, NEW_UNDERLINE_TEXT, NEW_UNDERLINE_SUBJECT, NEW_UNDERLINE_CONTENTS, NEW_UNDERLINE_DESCRIPTION, &LINK_RECT, REMOTE_FOLDER)

	getAnnotations(pdfApi, PDF_DOCUMENT, PAGE_NUMBER_EXTRACT, REMOTE_FOLDER)

	getAnnotation(pdfApi, PDF_DOCUMENT, ANNOTATION_ID, REMOTE_FOLDER)
}
