package main

func main() {
	pdfApi := initPdfApi()

	encryptDocument(pdfApi, PDF_DOCUMENT, PDF_OUTPUT, USER_PASSWORD, OWNER_PASSWORD, string(ENCRYPT_ALGORITHM), REMOTE_FOLDER)

	decryptDocument(pdfApi, PDF_DOCUMENT_ENCRYPTED, PDF_OUTPUT_DECRYPT, OWNER_PASSWORD, REMOTE_FOLDER)

	changeDocumentPasswords(pdfApi, PDF_DOCUMENT_ENCRYPTED, PDF_OUTPUT_ENCRYPTED_CHANGE, OWNER_PASSWORD, NEW_USER_PASSWORD, NEW_OWNER_PASSWORD, REMOTE_FOLDER)
}
