package main

func main() {
	pdfApi := initPdfApi()

	rotateDocumentPages(pdfApi, PDF_DOCUMENT, string(ROTATE_PAGES_ANGLE), ROTATE_PAGES, REMOTE_FOLDER)

	cropDocumentPage(pdfApi, PDF_DOCUMENT, CROP_PAGE_NUMBER, CROP_LLX, CROP_LLY, CROP_WIDTH, CROP_HEIGHT, CROP_LOCAL_RESULT_DOCUMENT_NAME, LOCAL_FOLDER, REMOTE_FOLDER)

	resizeAllPages(pdfApi, PDF_DOCUMENT, RESIZE_PDF_HTML_FILE, RESIZE_NEW_PAGE_WIDTH, RESIZE_NEW_PAGE_HEIGHT, RESIZE_RESULT_DOCUMENT_NAME, LOCAL_FOLDER, REMOTE_FOLDER)
}
