package main

func main() {
	pdfApi := initPdfApi(API_CLIENT_ID, API_CLIENT_SECRET)

	AppendNewPage(pdfApi, PDF_DOCUMENT, PDF_OUTPUT, REMOTE_FOLDER)

	ExtractPageInfo(pdfApi, PDF_DOCUMENT, PAGE_NUMBER, REMOTE_FOLDER)

	SavePageAsPNG(pdfApi, PDF_DOCUMENT, PAGE_NUMBER, PNG_PAGE_OUTPUT, REMOTE_FOLDER)

	MovePage(pdfApi, PDF_DOCUMENT, PAGE_NUMBER, PAGE_NUMBER+1, PDF_OUTPUT, REMOTE_FOLDER)

	DeletePage(pdfApi, PDF_DOCUMENT, PAGE_NUMBER, PDF_OUTPUT, REMOTE_FOLDER)

	AppendPageStampText(pdfApi, PDF_DOCUMENT, PAGE_NUMBER, PDF_OUTPUT, STAMP_TEXT, REMOTE_FOLDER)

	AppendPageStampImage(pdfApi, PDF_DOCUMENT, PDF_OUTPUT, IMAGE_STAMP_FILE, PAGE_NUMBER, IMAGE_STAMP_WIDTH, IMAGE_STAMP_HEIGHT, REMOTE_FOLDER)

	GetPagesWordsCount(pdfApi, PDF_DOCUMENT, REMOTE_FOLDER)
}
