package main

func main() {
	pdfApi := initPdfApi()

	appendLink(pdfApi, PDF_DOCUMENT, PDF_OUTPUT, PAGE_NUMBER, NEW_LINK_ACTION, &LINK_RECT, REMOTE_FOLDER)

	getLinks(pdfApi, PDF_DOCUMENT, PAGE_NUMBER, REMOTE_FOLDER)

	getLink(pdfApi, PDF_DOCUMENT, LINK_ID, REMOTE_FOLDER)

	removeLink(pdfApi, PDF_DOCUMENT, PDF_OUTPUT_REMOVE, LINK_ID, REMOTE_FOLDER)

	replaceLink(pdfApi, PDF_DOCUMENT, PDF_OUTPUT_REPLACE, LINK_ID, NEW_LINK_ACTION, REMOTE_FOLDER)
}
